services:
  web:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - ${environment}.env
    ports:
      - "${LISTEN_PORT}:${SERVICE_PORT}"
  db:
    image: "postgres:alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pg_password
      - POSTGRES_DB=myapp
    ports:
      - "5432:5432"
    volumes:
      - database/data/dev:/var/lib/postgresql/data


