"""movie detail: year genre director actors plot

Revision ID: 2c4970e2c27f
Revises: 56d230517330
Create Date: 2026-07-07 22:12:13.120899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c4970e2c27f'
down_revision: Union[str, Sequence[str], None] = '56d230517330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('director', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('actors', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('plot', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('plot')
        batch_op.drop_column('actors')
        batch_op.drop_column('director')
        batch_op.drop_column('genre')
        batch_op.drop_column('year')

    # ### end Alembic commands ###
