"""movie tracker: on_watchlist + on_rankings

Revision ID: 56d230517330
Revises: a3732379d384
Create Date: 2026-07-07 20:18:49.378692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56d230517330'
down_revision: Union[str, Sequence[str], None] = 'a3732379d384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema and backfill the two lists from the legacy completed flag."""
    # Add with a server_default so existing rows are populated, then backfill.
    with op.batch_alter_table('user_movies', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'on_watchlist',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(
            sa.Column(
                'on_rankings',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    # Legacy import: completed=1 => the ranked/watched list; otherwise watchlist.
    op.execute('UPDATE user_movies SET on_rankings = TRUE WHERE completed = 1')
    op.execute(
        'UPDATE user_movies SET on_watchlist = TRUE '
        'WHERE completed = 0 OR completed IS NULL'
    )

    # Drop the server defaults now that existing rows are populated; the app
    # model supplies the default on insert.
    with op.batch_alter_table('user_movies', schema=None) as batch_op:
        batch_op.alter_column('on_watchlist', server_default=None)
        batch_op.alter_column('on_rankings', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_movies', schema=None) as batch_op:
        batch_op.drop_column('on_rankings')
        batch_op.drop_column('on_watchlist')

    # ### end Alembic commands ###
