"""initial schema

Revision ID: a3732379d384
Revises:
Create Date: 2026-07-07 08:08:30.625994

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a3732379d384'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'books',
        sa.Column('title', sa.String(length=254), nullable=False),
        sa.Column('isbn', sa.String(length=20), nullable=True),
        sa.Column('googleid', sa.String(length=254), nullable=True),
        sa.Column('poster_url', sa.String(length=254), nullable=True),
        sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('pk'),
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_books_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_books_pk'), ['pk'], unique=False)

    op.create_table(
        'countries',
        sa.Column('title', sa.String(length=255), nullable=True),
        sa.Column('country_code', sa.String(length=4), nullable=True),
        sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('pk'),
        sa.UniqueConstraint('country_code'),
    )
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_countries_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_countries_pk'), ['pk'], unique=False)

    op.create_table(
        'movies',
        sa.Column('title', sa.String(length=255), nullable=True),
        sa.Column('imdb', sa.String(length=40), nullable=True),
        sa.Column('release_date', sa.DateTime(), nullable=True),
        sa.Column('rating_imdb', sa.Float(), nullable=True),
        sa.Column('runtime', sa.Integer(), nullable=True),
        sa.Column('language', sa.String(length=40), nullable=True),
        sa.Column('rated', sa.String(length=11), nullable=True),
        sa.Column('poster_url', sa.String(length=500), nullable=True),
        sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('pk'),
        sa.UniqueConstraint('imdb'),
    )
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movies_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_movies_pk'), ['pk'], unique=False)

    op.create_table(
        'tv_shows',
        sa.Column('title', sa.String(length=254), nullable=False),
        sa.Column('imdb', sa.String(length=254), nullable=True),
        sa.Column('tvmaze', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=254), nullable=True),
        sa.Column('poster_url', sa.String(length=254), nullable=True),
        sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('pk'),
        sa.UniqueConstraint('imdb'),
    )
    with op.batch_alter_table('tv_shows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tv_shows_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_tv_shows_pk'), ['pk'], unique=False)

    op.create_table(
        'users',
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('display_name', sa.String(length=30), nullable=True),
        sa.Column('user_group', sa.String(), nullable=True),
        sa.Column('password', sa.String(), nullable=True),
        sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('pk'),
        sa.UniqueConstraint('email'),
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_pk'), ['pk'], unique=False)

    op.create_table(
        'video_games',
        sa.Column('title', sa.String(length=255), nullable=True),
        sa.Column('igdb', sa.Integer(), nullable=True),
        sa.Column('poster_url', sa.String(length=100), nullable=True),
        sa.Column('release_date', sa.DateTime(), nullable=True),
        sa.Column('rating', sa.Float(), nullable=True),
        sa.Column('time_to_beat', sa.Integer(), nullable=True),
        sa.Column('igdb_last_update', sa.DateTime(), nullable=True),
        sa.Column('slug', sa.String(length=255), nullable=True),
        sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('pk'),
        sa.UniqueConstraint('igdb'),
    )
    with op.batch_alter_table('video_games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_games_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_video_games_pk'), ['pk'], unique=False)

    op.create_table(
        'tv_episodes',
        sa.Column('title', sa.String(length=254), nullable=False),
        sa.Column('tvmaze', sa.Integer(), nullable=True),
        sa.Column('tv_show_id', sa.Integer(), nullable=False),
        sa.Column('airdate', sa.DateTime(), nullable=True),
        sa.Column('season', sa.Integer(), nullable=True),
        sa.Column('season_number', sa.Integer(), nullable=True),
        sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['tv_show_id'],
            ['tv_shows.pk'],
        ),
        sa.PrimaryKeyConstraint('pk'),
        sa.UniqueConstraint('tvmaze'),
    )
    with op.batch_alter_table('tv_episodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tv_episodes_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_tv_episodes_pk'), ['pk'], unique=False)

    op.create_table(
        'user_books',
        sa.Column('book_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('rank', sa.Integer(), nullable=True),
        sa.Column('completed', sa.Integer(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['book_id'],
            ['books.pk'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.pk'],
        ),
        sa.PrimaryKeyConstraint('pk'),
    )
    with op.batch_alter_table('user_books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_books_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_books_pk'), ['pk'], unique=False)

    op.create_table(
        'user_countries',
        sa.Column('country_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('rank', sa.Integer(), nullable=True),
        sa.Column('completed', sa.Integer(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('first_visited', sa.DateTime(), nullable=True),
        sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['country_id'],
            ['countries.pk'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.pk'],
        ),
        sa.PrimaryKeyConstraint('pk'),
    )
    with op.batch_alter_table('user_countries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_countries_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_countries_pk'), ['pk'], unique=False)

    op.create_table(
        'user_movies',
        sa.Column('movie_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('rank', sa.Integer(), nullable=True),
        sa.Column('completed', sa.Integer(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['movie_id'],
            ['movies.pk'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.pk'],
        ),
        sa.PrimaryKeyConstraint('pk'),
    )
    with op.batch_alter_table('user_movies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_movies_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_movies_pk'), ['pk'], unique=False)

    op.create_table(
        'user_tv_shows',
        sa.Column('tv_show_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('rank', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=254), nullable=True),
        sa.Column('freeze', sa.Integer(), nullable=True),
        sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['tv_show_id'],
            ['tv_shows.pk'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.pk'],
        ),
        sa.PrimaryKeyConstraint('pk'),
    )
    with op.batch_alter_table('user_tv_shows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_tv_shows_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_tv_shows_pk'), ['pk'], unique=False)

    op.create_table(
        'user_video_games',
        sa.Column('game_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('rank', sa.Integer(), nullable=True),
        sa.Column('completed', sa.Integer(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('is_100_percent', sa.Boolean(), nullable=True),
        sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['game_id'],
            ['video_games.pk'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.pk'],
        ),
        sa.PrimaryKeyConstraint('pk'),
    )
    with op.batch_alter_table('user_video_games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_video_games_id'), ['id'], unique=True)
        batch_op.create_index(
            batch_op.f('ix_user_video_games_pk'), ['pk'], unique=False
        )

    op.create_table(
        'user_tv_episodes',
        sa.Column('episode_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('watched', sa.Integer(), nullable=True),
        sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['episode_id'],
            ['tv_episodes.pk'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.pk'],
        ),
        sa.PrimaryKeyConstraint('pk'),
    )
    with op.batch_alter_table('user_tv_episodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_tv_episodes_id'), ['id'], unique=True)
        batch_op.create_index(
            batch_op.f('ix_user_tv_episodes_pk'), ['pk'], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tv_episodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_tv_episodes_pk'))
        batch_op.drop_index(batch_op.f('ix_user_tv_episodes_id'))

    op.drop_table('user_tv_episodes')
    with op.batch_alter_table('user_video_games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_video_games_pk'))
        batch_op.drop_index(batch_op.f('ix_user_video_games_id'))

    op.drop_table('user_video_games')
    with op.batch_alter_table('user_tv_shows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_tv_shows_pk'))
        batch_op.drop_index(batch_op.f('ix_user_tv_shows_id'))

    op.drop_table('user_tv_shows')
    with op.batch_alter_table('user_movies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_movies_pk'))
        batch_op.drop_index(batch_op.f('ix_user_movies_id'))

    op.drop_table('user_movies')
    with op.batch_alter_table('user_countries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_countries_pk'))
        batch_op.drop_index(batch_op.f('ix_user_countries_id'))

    op.drop_table('user_countries')
    with op.batch_alter_table('user_books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_books_pk'))
        batch_op.drop_index(batch_op.f('ix_user_books_id'))

    op.drop_table('user_books')
    with op.batch_alter_table('tv_episodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tv_episodes_pk'))
        batch_op.drop_index(batch_op.f('ix_tv_episodes_id'))

    op.drop_table('tv_episodes')
    with op.batch_alter_table('video_games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_games_pk'))
        batch_op.drop_index(batch_op.f('ix_video_games_id'))

    op.drop_table('video_games')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_pk'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('tv_shows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tv_shows_pk'))
        batch_op.drop_index(batch_op.f('ix_tv_shows_id'))

    op.drop_table('tv_shows')
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movies_pk'))
        batch_op.drop_index(batch_op.f('ix_movies_id'))

    op.drop_table('movies')
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_countries_pk'))
        batch_op.drop_index(batch_op.f('ix_countries_id'))

    op.drop_table('countries')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_pk'))
        batch_op.drop_index(batch_op.f('ix_books_id'))

    op.drop_table('books')
    # ### end Alembic commands ###
