services:
  postgres-dev:
    container_name: ${LZ}_phoenix_db_${API_ENV}
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - env/${API_ENV}.env
    volumes:
      - ./database/data/${API_ENV}:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_EXPOSED_PORT}:${POSTGRES_PORT}"
