name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        pip install black pylint pytest pytest-cov openapi-spec-validator

    - name: Run Black
      run: |
        source .venv/bin/activate
        black --skip-string-normalization .

    - name: Run Pylint
      run: |
        source .venv/bin/activate
        ./.venv/bin/pylint --ignore-patterns=.venv --disable=too-few-public-methods .

    - name: Run Pytest
      run: |
        source .venv/bin/activate
        ./.venv/bin/pytest --cov=./ --cov-report=html  --cov-report=term --junitxml=reports/junit/test-results.html

    - name: Validate OpenAPI Spec
      run: |
        source .venv/bin/activate
        openapi-spec-validator openapi.json

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: reports/junit/test-results.html

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.html
