name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.1"
        cache: 'poetry'

    - name: Install Poetry
      run: |
        pip install --upgrade pip
        pip install poetry

    - name: Install dependencies
      run: |
        poetry install --with dev --no-root

    - name: Run Black
      run: |
        poetry run black --skip-string-normalization .

    - name: Run Pylint
      run: |
        poetry run pylint .

    - name: Validate OpenAPI Spec
      run: |
        poetry run openapi-spec-validator openapi.json
