name: Snyk Security

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.1"

      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry


      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Snyk SCA Scan
        run: |
          source .venv/bin/activate
          snyk test --file=requirements/base.txt --package-manager=pip --fail-on=patchable --sarif > snyk-sca.sarif

      - name: Snyk SAST Scan
        run: |
          source .venv/bin/activate
          snyk code test --all-projects --exclude=tests --sarif > snyk-sast.sarif

      - name: Snyk Open Source monitor
        run: |
          source .venv/bin/activate
          snyk monitor --file=requirements/base.txt --package-manager=pip

      - name: Upload SAST result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-sast.sarif

      - name: Upload SCA result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-sca.sarif
