name: Snyk Security

on:
  pull_request:
    branches: ["main"]
    types: [ labeled ]

permissions:
  contents: read

jobs:
  snyk:
    # Only run if the label 'scan' is added to the PR
    if: ${{ github.event.label.name == 'scan' }}
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
            python -m venv .venv
            source .venv/bin/activate
            pip install -r requirements/base.txt

      - name: Snyk SCA Scan
        run: |
            source .venv/bin/activate
            snyk test --all-projects --exclude=tests --fail-on=patchable

      - name: Snyk SAST Scan
        run: |
            source .venv/bin/activate
            snyk code test --all-projects --exclude=tests
