name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      ENV: github

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements/test.txt

    - name: Run Pytest
      run: |
          source .venv/bin/activate
          ./.venv/bin/pytest --cov=./ --cov-report=html:.reports/coverage --cov-report=term --html=.reports/junit/test-results.html


    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: .reports/junit/test-results.html
        retention-days: 60

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: .reports/coverage
        retention-days: 60
